dist: trusty
sudo: required
language: go

go:
  - 1.11.x

matrix:
  allow_failures:
    - go: master

env:
  global:
    - SERVICE_NAME=mongodb_exporter
    - VERSION_NUMBER=$(./ci/version.sh)
    - DOCKER_TAG_NAME=mongodb_exporter

services:
  - docker

script:
   - make 
#   - ./ci/build-image.sh 

deploy:
#  - provider: script
#    script: ./ci/push_image.sh
#    on:
#      all_branches: true
#      condition: $TRAVIS_BRANCH =~ ^(master|test)$ && $TRAVIS_PULL_REQUEST = "false"
  - provider: s3
    region: eu-west-1
    bucket: yle-mongodb-exporter
    file_glob: true
    file: 
        - mongodb_exporter
    upload-dir: $SERVICE_NAME/s3
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|test)$ && $TRAVIS_PULL_REQUEST = "false"
 

