dist: trusty
sudo: required
language: go

go:
  - 1.10.x

matrix:
  allow_failures:
    - go: master

env:
  global:
    - SERVICE_NAME=mongodb_exporter
    - VERSION_NUMBER=$(./ci/version.sh)
    - DOCKER_TAG_NAME=mongodb_exporter
    - STATIC_DIR=.s3-static
    - TEST_MONGODB_URI=""

services:
  - docker

script:
  # ensure that vendor/ is in sync with code and Gopkg.*
#  - curl https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -L -o ${TRAVIS_HOME}/dep && chmod +x ${TRAVIS_HOME}/dep
#  - rm -fr vendor/
#  - ~/dep ensure -v
#  - git diff --exit-code

   - make 
#  - docker run --rm -v "$PWD":/go/src/github.com/percona/mongodb_exporter -w /go/src/github.com/percona/mongodb_exporter golang make build
   

